[project]
name = "rayleigh-analysis"
version = "0.1.0"
description = ""
authors = [
    {name = "EdwardBerman",email = "10emb29@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10,<4.0"

[tool.poetry]
name = "rayleigh-analysis"
version = "0.1.0"
packages = [
  { include = "metrics", from = "." },
  { include = "train", from = "." },
  { include = "model", from = "." },
  { include = "data_preprocessing", from = "." },
  { include = "parsers", from = "." },
  { include = "external", from = "." }
]

[[tool.poetry.source]]
name = "pyg-cu124"
url = "https://data.pyg.org/whl/torch-2.5.1+cu124.html"
priority = "explicit"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
