[project]
name = "rayleigh-analysis"
version = "0.1.0"
description = ""
authors = [
    {name = "EdwardBerman",email = "10emb29@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "torch-geometric (>=2.6.1,<3.0.0)",
    "wandb (>=0.22.0,<0.23.0)",
    "weave (>=0.52.8,<0.53.0)",
    "simple-parsing (>=0.1.7,<0.2.0)",
    "torch (==2.7.1+cu126)"
]

[tool.poetry]
packages = [{include = "rayleigh_analysis", from = "src"}]

[[tool.poetry.source]]
name = "pyg-cu124"
url = "https://data.pyg.org/whl/torch-2.5.1+cu124.html"
priority = "explicit"


[[tool.poetry.source]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
priority = "explicit"


[[tool.poetry.source]]
name = "pyg-cu126"
url = "https://data.pyg.org/whl/torch-2.7.1+cu126.html"
priority = "explicit"


[tool.poetry.dependencies]
torch = {source = "pytorch-cu126"}
[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
