_wandb:
    value:
        cli_version: 0.22.1
        e:
            8fymago3ihi1rjxopkuo8a0bxw71z9dx:
                args:
                    - --dataset
                    - COCO-SP
                    - --architecture
                    - CRAWL
                    - --num_layers
                    - "12"
                    - --activation_function
                    - ReLU
                    - --batch_size
                    - "64"
                    - --batch_norm
                    - BatchNorm
                    - --num_attention_heads
                    - "2"
                    - --dropout_rate
                    - "0.1"
                    - --hidden_size
                    - "128"
                    - --edge_aggregator
                    - NONE
                    - --optimizer
                    - Adam
                    - --lr
                    - "0.001"
                    - --epochs
                    - "750"
                    - --weight_decay
                    - "0.0"
                    - --window_size
                    - "4"
                    - --receptive_field
                    - "5"
                    - --save_dir
                    - output
                cpu_count: 28
                cpu_count_logical: 28
                cudaVersion: "12.3"
                disk:
                    /:
                        total: "62847451136"
                        used: "7101775872"
                executable: /home/li.tao/.cache/pypoetry/virtualenvs/rayleigh-analysis-FI45fQBK-py3.13/bin/python3
                git:
                    commit: 25d053b995b3b2cac54336a4ad42b7afea8afdff
                    remote: git@github.com:EdwardBerman/rayleigh_analysis.git
                gpu: Tesla V100-SXM2-32GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-SXM2-32GB
                      uuid: GPU-97160267-8972-d558-fac8-8136a8ec4909
                host: d1017
                memory:
                    total: "200811175936"
                os: Linux-5.14.0-362.13.1.el9_3.x86_64-x86_64-with-glibc2.34
                program: -m train.train
                python: CPython 3.13.5
                root: /projects/gllab/li.tao/rayleigh_analysis
                slurm:
                    cluster_name: explorer
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x0000002
                    cpu_bind_list: "0x0000002"
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "1"
                    distribution: cyclic
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: rwalters
                    job_cpus_per_node: "1"
                    job_end_time: "1759692065"
                    job_gid: "100"
                    job_group: users
                    job_id: "2181604"
                    job_name: bash
                    job_nodelist: d1017
                    job_num_nodes: "1"
                    job_partition: gpu
                    job_qos: normal
                    job_start_time: "1759677665"
                    job_uid: "1825818491"
                    job_user: li.tao
                    jobid: "2181604"
                    launch_node_ipaddr: 10.99.200.107
                    localid: "0"
                    mem_per_node: "4096"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: d1017
                    nprocs: "1"
                    ntasks: "1"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "46293"
                    pty_win_col: "103"
                    pty_win_row: "51"
                    script_context: prolog_task
                    srun_comm_host: 10.99.200.107
                    srun_comm_port: "43997"
                    step_gpus: "2"
                    step_id: "0"
                    step_launcher_port: "43997"
                    step_nodelist: d1017
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /home/li.tao
                    submit_host: explorer-02
                    task_pid: "525215"
                    tasks_per_node: "1"
                    topology_addr: d1017
                    topology_addr_pattern: node
                    umask: "0022"
                startedAt: "2025-10-05T16:55:19.213601Z"
                writerId: 8fymago3ihi1rjxopkuo8a0bxw71z9dx
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 77
            "2":
                - 1
                - 77
            "3":
                - 16
            "4": 3.13.5
            "5": 0.22.1
            "12": 0.22.1
            "13": linux-x86_64
architecture:
    value: CRAWL
dataset:
    value: COCO-SP
epochs:
    value: 750
learning_rate:
    value: 0.001
